version: "3"
services:
  jtsdns:
    image: phaldan/jtsdns:1.6.0@sha256:16b90d1ba4bc5016e3c1f8dd402dee0ce61654efcb925c74b547613303844605
    ports:
      - "41144:41144"
    volumes:
      - ./log:/JTSDNS/log
    environment:
      - JTSDNS_MYSQL_HOST=mysql
      - JTSDNS_MYSQL_USER=root
      - JTSDNS_MYSQL_PASSWORD=changeme
      - JTSDNS_MYSQL_DATABASE=jtsdns
      - JTSDNS_LOGFILE=%apphome%log/JTSDNS.log
    links:
      - mysql
  mysql:
    image: mariadb:10.4.6@sha256:084ee945df05cdbfe6eb3a9d96bc12a2002c500e4550d1bcff2fcdbf93ce96a7
    environment:
      - MYSQL_DATABASE=jtsdns
      - MYSQL_ROOT_PASSWORD=changeme
    volumes:
      - ./mysql:/var/lib/mysql
