version: "3"
services:
  jtsdns:
    image: phaldan/jtsdns:1.6.0@sha256:16b90d1ba4bc5016e3c1f8dd402dee0ce61654efcb925c74b547613303844605
    ports:
      - "41144:41144"
    volumes:
      - ./log:/JTSDNS/log
    environment:
      - JTSDNS_MYSQL_HOST=mysql
      - JTSDNS_MYSQL_USER=root
      - JTSDNS_MYSQL_PASSWORD=changeme
      - JTSDNS_MYSQL_DATABASE=jtsdns
      - JTSDNS_LOGFILE=%apphome%log/JTSDNS.log
    links:
      - mysql
  mysql:
    image: mariadb:10.4.6@sha256:33e9f35b1b1a2ed4254dbcc887cbf1f4b3d8a988d8d716372fa559c5f3aeafc8
    environment:
      - MYSQL_DATABASE=jtsdns
      - MYSQL_ROOT_PASSWORD=changeme
    volumes:
      - ./mysql:/var/lib/mysql
