version: "3"
services:
  jtsdns:
    image: phaldan/jtsdns:1.6.0@sha256:16b90d1ba4bc5016e3c1f8dd402dee0ce61654efcb925c74b547613303844605
    ports:
      - "41144:41144"
    volumes:
      - ./log:/JTSDNS/log
    environment:
      - JTSDNS_MYSQL_HOST=mysql
      - JTSDNS_MYSQL_USER=root
      - JTSDNS_MYSQL_PASSWORD=changeme
      - JTSDNS_MYSQL_DATABASE=jtsdns
      - JTSDNS_LOGFILE=%apphome%log/JTSDNS.log
    links:
      - mysql
  mysql:
    image: mariadb:13.0.2@sha256:d4fdec0510ad498e4f3127da30a99df3745bd6d5e611ae6ac5f76403d9284a8d
    environment:
      - MYSQL_DATABASE=jtsdns
      - MYSQL_ROOT_PASSWORD=changeme
    volumes:
      - ./mysql:/var/lib/mysql
