version: "3"
services:
  jtsdns:
    image: phaldan/jtsdns:1.6.0@sha256:16b90d1ba4bc5016e3c1f8dd402dee0ce61654efcb925c74b547613303844605
    ports:
      - "41144:41144"
    volumes:
      - ./log:/JTSDNS/log
    environment:
      - JTSDNS_MYSQL_HOST=mysql
      - JTSDNS_MYSQL_USER=root
      - JTSDNS_MYSQL_PASSWORD=changeme
      - JTSDNS_MYSQL_DATABASE=jtsdns
      - JTSDNS_LOGFILE=%apphome%log/JTSDNS.log
    links:
      - mysql
  mysql:
    image: mariadb:10.6.0@sha256:718cb856543ae92a5460997ed57e8ec398f478beb0110fe5efe675f1f14d6bd8
    environment:
      - MYSQL_DATABASE=jtsdns
      - MYSQL_ROOT_PASSWORD=changeme
    volumes:
      - ./mysql:/var/lib/mysql
